# Autogenerated wrapper script for Vim_jll for armv6l-linux-musleabihf
export vim

using Ncurses_jll
using Libiconv_jll
JLLWrappers.@generate_wrapper_header("Vim")
JLLWrappers.@declare_executable_product(vim)
function __init__()
    JLLWrappers.@generate_init_header(Ncurses_jll, Libiconv_jll)
    JLLWrappers.@init_executable_product(
        vim,
        "bin/vim",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
