# Autogenerated wrapper script for Vim_jll for i686-w64-mingw32
export gvim

using Ncurses_jll
using Libiconv_jll
JLLWrappers.@generate_wrapper_header("Vim")
JLLWrappers.@declare_executable_product(gvim)
function __init__()
    JLLWrappers.@generate_init_header(Ncurses_jll, Libiconv_jll)
    JLLWrappers.@init_executable_product(
        gvim,
        "bin\\gvim.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
